name    'bjoernalbers-mysql_osx'
version '0.0.1'
author 'bjoernalbers'
license 'Apache License, Version 2.0'
summary 'Manage MySQL Server on Mac OS X.'
description '(Please visit the project page!)'
project_page 'https://github.com/bjoernalbers/puppet-mysql_osx'
dependency 'bjoernalbers/homebrew', '>= 0.0.2'
